pipeline {
    // 'any' roda em qualquer agente disponível. 
    // Se sua empresa usa labels (ex: 'linux-aws'), troque 'any' por { label 'linux-aws' }
    agent any 

    parameters {
        // Seletor de Perfil AWS (Configurado no ~/.aws/config do servidor Jenkins)
        choice(name: 'AWS_PROFILE', choices: ['default', 'dev-profile', 'prod-profile'], description: 'Selecione o Profile AWS configurado no Agente')
        
        choice(name: 'OPERATION_MODE', choices: ['FULL_MIGRATION', 'BACKUP_ONLY', 'RESTORE_ONLY'], description: 'Selecione o tipo de operação')
        string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'Região AWS')
        
        string(name: 'CLUSTER_SOURCE_NAME', defaultValue: '', description: 'Cluster ORIGEM')
        string(name: 'CLUSTER_DEST_NAME', defaultValue: '', description: 'Cluster DESTINO')
        
        string(name: 'BACKUP_NAME_TO_RESTORE', defaultValue: '', description: 'Nome do Backup (Apenas p/ RESTORE_ONLY)')
        
        string(name: 'VELERO_BUCKET_NAME', description: 'Nome do Bucket S3')
        string(name: 'VELERO_ROLE_ARN', description: 'ARN da Role IAM')
        
        string(name: 'ISTIO_SYNC_MODE', defaultValue: 'all', description: "'all', 'none' ou lista")
    }

    stages {
        stage('Preparar Ambiente') {
            steps {
                // Opcional: Garante que as libs python estão instaladas no agente
                // Se o agente for compartilhado e não puder instalar coisas globais, 
                // recomendamos usar um virtualenv (venv), mas aqui vou simplificar:
                sh 'pip3 install boto3 kubernetes requests --user || pip3 install boto3 kubernetes requests'
            }
        }

        stage('Executar Migração') {
            steps {
                // Roda direto no shell da máquina
                sh 'python3 -u migracao_jenkins.py'
            }
        }
    }
}
